onlyBuiltDependencies:
  - '@swc/core'
  - cypress
  - es5-ext
  - esbuild
  - msw
  - protobufjs

minimumReleaseAgeExclude:
  - '@navikt/*'

allowBuilds:
  cypress: true
  esbuild: true
  msw: true

overrides:
  decode-uri-component@<=0.4.2: ^0.5.0
