apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brillekalkulator
    team: teamdigihot
  name: hm-brillekalkulator
  namespace: teamdigihot
spec:
  image: {{image}}
  team: teamdigihot
  port: 5000
  ingresses:
    - https://brille.intern.dev.nav.no/hjelpemidler/brillekalkulator
  liveness:
    path: /hjelpemidler/brillekalkulator/internal/isalive
  readiness:
    path: /hjelpemidler/brillekalkulator/internal/isready
  prometheus:
    enabled: true
    path: /hjelpemidler/brillekalkulator/internal/metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: BRILLE_API_BASE_URL
      value: 'http://hm-brille-api.teamdigihot.svc.cluster.local'
    - name: PORT
      value: '5000'
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      rules:
        - application: hm-brille-api
