apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brillekalkulator-labs
    team: teamdigihot
  name: hm-brillekalkulator-labs
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://brille-labs.ekstern.dev.nav.no/hjelpemidler/brillekalkulator
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: false
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 300Mi
  env:
    - name: BRILLE_API_BASE_URL
      value: ''
    - name: BRILLE_API_TARGET_AUDIENCE
      value: ''
    - name: USE_MSW
      value: 'true'
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.ekstern.dev.nav.no
