apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brillekalkulator
    team: teamdigihot
  name: hm-brillekalkulator
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://www.nav.no/hjelpemidler/brillekalkulator
  liveness:
    path: isalive
  readiness:
    path: isready
  prometheus:
    enabled: false
    path: metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: BRILLE_API_BASE_URL
      value: 'http://hm-brille-api.teamdigihot.svc.cluster.local'
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      rules:
        - application: hm-brille-api
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: www.nav.no
